[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]
via_ir = true
optimizer = true
optimizer_runs = 1

[rpc_endpoints]
# TODO: Replace with the exact Arc Testnet/Mainnet RPC provided by ETHGlobal
arc = "https://rpc.testnet.arc.network"

[etherscan]
arc = { key = "${ARC_API_KEY}", url = "https://explorer.arc.network/api" }
